{
 "title": "Monitoring Project Dashboard",
 "tags": [
  "devops",
  "monitoring",
  "flask"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Flask request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flask_app_requests_total[1m]))",
     "legendFormat": "requests/sec"
    }
   ]
  },
  {
   "title": "Flask requests total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "flask_app_requests_total", "legendFormat": "{{endpoint}} {{http_status}}" }
   ]
  },
  {
   "title": "Flask application logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"flask-app\"}"
    }
   ]
  }
 ]
}